Разметка главной страницы
htmlacademy-htmlcss/1710673-sedona-30 pull request #1
Opened 2021-02-01 12:04 UTC by khorava021

2021-02-01 21:18 UTC, dean992008 requested changes

2021-02-01 21:18 UTC, dean992008 commented on index.html
> +        <a>
Лого нужно вынести из `nav`. 
https://up.htmlacademy.ru/htmlcss/30/project/sedona#sedona-3-2

2021-02-01 21:18 UTC, dean992008 commented on index.html
> +        <h1>Welcom</h1>
- Текст на фоне гор нужно добавить как картинкой, так как там много разных шрифтов и неоправдано подркочать их все. 
- h1 должен описывать то что происходит на странице, `welcome` для этого не совсем подходит. Если такого заголовка нет на макете, его нужно сделать, а потом с помощью CSS скрыть доступно.

2021-02-01 21:18 UTC, dean992008 commented on index.html
> +        <img src="https://via.placeholder.com" width="1200" hight="509" alt="Background photo">
Фоновые картники нужно будет добавлять через CSS. Пока нужно удалить.

2021-02-01 21:18 UTC, dean992008 commented on index.html
> +        <h2>Седона — небольшой городок в Аризоне,<br>
- `br` нужно использовать только в крайнем случае, если по другому никак. Пока нужно удалить, и если понадобится добавить на этапе pixel perfect. 
- В данном случае это не заголовок, а просто текст, тоже нужно сделать скрытым с текстом например: `5 причин, по которым Седона круче, чем Гранд Каньон`

2021-02-01 21:18 UTC, dean992008 commented on index.html
> +      <section>
Это все 1 большая секция http://joxi.ru/eAO1kMkt9R113m

2021-02-01 21:18 UTC, dean992008 commented on index.html
> +        <p>-№1-</p>
- Полоски нужно удалить их нужно будет добавить через css.

2021-02-01 21:18 UTC, dean992008 commented on index.html
> +      <section>
Причины нужно сделать номерованым списком: http://joxi.ru/a2XQMDMcwznnXA. `6` нужно сделать подсписком с 3 элементов.

2021-02-01 21:18 UTC, dean992008 commented on index.html
> +        <h2>Заинтересовались?</h2>
Тоже самое `Заинтересовались?` не описывает о чем блок. 
Проверить структуру заголовком можно здесь: https://yoksel.github.io/html-tree/. При чтении заголовков нужно примерно понимать о чем сайт не видя его.

2021-02-01 21:18 UTC, dean992008 commented on index.html
> +          <h3>Контактная информаци</h3>
Здесь правильнее использовать h2

2021-02-01 21:18 UTC, dean992008 commented on index.html
> +        <section>
Секция 1 в футере, поэтому ее можно не писать.

2021-02-01 21:18 UTC, dean992008 commented on index.html
> +            ТЕЛ: +7(495) 666-01-66</p>
Номер телефона нужно обернуть в сылку: https://up.htmlacademy.ru/htmlcss/30/criteries#d29

2021-02-01 21:18 UTC, dean992008 commented on index.html
> +              <a href="https://htmlacademy.ru">
Сылку нужно открывать в новой вкладке.

2021-02-01 21:18 UTC, dean992008 commented on index.html
> +                <img src="https://via.placeholder.com" width="113.98" hight="39.78" alt="Логотип HTML Academy">
Для размеров картинок нужно использовать целые числа.

2021-02-01 23:20 UTC, khorava021 commented on index.html
> +        <a>
Вынести из <nav>, но оставить в <header>, верно?

2021-02-01 23:21 UTC, khorava021 commented on index.html
> +        <img src="https://via.placeholder.com" width="1200" hight="509" alt="Background photo">
Исправлено.

2021-02-01 23:22 UTC, khorava021 commented on index.html
> +                <img src="https://via.placeholder.com" width="113.98" hight="39.78" alt="Логотип HTML Academy">
Я использовал те числа, что были в предоставлены у данного лого макете. 
Исправлено.

2021-02-01 23:22 UTC, khorava021 commented on index.html
> +              <a href="https://htmlacademy.ru">
Исправлено.

2021-02-01 23:22 UTC, khorava021 commented on index.html
> +            ТЕЛ: +7(495) 666-01-66</p>
Исправлено.

2021-02-01 23:22 UTC, khorava021 commented on index.html
> +        <section>
Исправлено.

2021-02-01 23:22 UTC, khorava021 commented on index.html
> +          <h3>Контактная информаци</h3>
Исправлено.

2021-02-01 23:26 UTC, khorava021 commented on index.html
> +        <h2>Заинтересовались?</h2>
Тут тоже вместо <h*> следует указать "Заинтересовались?" как обычный текст через тег <p>?
Если да, то уже исправил.

2021-02-01 23:31 UTC, khorava021 commented on index.html
> +        <p>-№1-</p>
Исправлено.

2021-02-01 23:31 UTC, khorava021 commented on index.html
> +      <section>
Я правильно понял, что после первого заголовка, мне следует всё "пихнуть" в одну секцию и закрыть её перед заголовком "Заинтересовались?"?

2021-02-01 23:32 UTC, khorava021 commented on index.html
> +        <h2>Седона — небольшой городок в Аризоне,<br>
Исправлено.

2021-02-01 23:37 UTC, khorava021 commented on index.html
> +        <h1>Welcom</h1>
Например такой заголовок: 
<h1>Отдых в Седоне!</h1>

А на счёт того, что текст гор добавить следует как картинку, я об этом думал, но не совсем понял как это лучше сделать. Единственное что мне пришло в голову - это добавить его, как все остальные картинки, через заглушку и просто дополнить альтом.

2021-02-02 08:42 UTC, dean992008 commented on index.html
> +        <a>
Да.

2021-02-02 08:44 UTC, dean992008 commented on index.html
> +        <h1>Welcom</h1>
Да, пока можно сделать как заглушку. А когда будешь делать задание о картинках выделишь все слои и эуспортируешь как PNG.

2021-02-02 08:44 UTC, khorava021 commented on index.html
> +        <a>
Исправлено.

2021-02-02 08:45 UTC, dean992008 commented on index.html
> +      <section>
Да, эти блоки обьеденены по смыслу, и если 1 из них перенести или удалить это сломает логику. А секция какраз подразумесает что если ее удалить, логика и структура не изменится.

2021-02-02 08:47 UTC, dean992008 commented on index.html
> +        <h2>Заинтересовались?</h2>
Да для `Заинтересовались?` используем `p` а перед ним нужно сделать заголовок который потом скроем, например 'Поиск гостиниц'

2021-02-02 09:05 UTC, khorava021 commented on index.html
> +        <h2>Заинтересовались?</h2>
Исправлено.

2021-02-02 09:09 UTC, khorava021 commented on index.html
> +      <section>
Исправлено.

2021-02-02 09:14 UTC, khorava021 commented on index.html
> +        <h1>Welcom</h1>
Исправлено.

2021-02-16 13:11 UTC, dean992008 commented on index.html
> +    <ol>
Здесь должен быть li. Должна получиться структура: `ul > li > h2 + ul > li`. Также после правок нужно выполнить автоформатирование.

2021-02-16 13:12 UTC, dean992008 commented
Я прийму это задание так как осталать всего 1 ошибка, а ты поправь вместе со следующим заданием.

2021-02-16 13:12 UTC, merged